import {useEffect,useState,type FormEvent} from 'react';
import axios from 'axios';
import {Link,Route,Routes,useNavigate} from 'react-router-dom';
const api=axios.create({baseURL:import.meta.env.VITE_API_URL||'http://localhost:8000/api'});
api.interceptors.request.use(c=>{const t=localStorage.getItem('rf_token');if(t)c.headers.Authorization=`Bearer ${t}`;return c});

type User={id:number;email:string};
type Doc={id:number;filename:string;status:string;chunk_count:number;error_message?:string};
function Auth({onLogin}:{onLogin:(u:User)=>void}){const[email,setEmail]=useState('');const[pw,setPw]=useState('');const[register,setRegister]=useState(false);const[error,setError]=useState('');async function submit(e:FormEvent){e.preventDefault();try{const r=await api.post(register?'/auth/register':'/auth/login',{email,password:pw});localStorage.setItem('rf_token',r.data.access_token);onLogin(r.data.user)}catch(e:any){setError(e.response?.data?.detail||'Request failed')}}return <div className="auth"><form className="card authbox" onSubmit={submit}><h1>RAG<span>Forge</span></h1><p>Production RAG Intelligence Platform</p><input required type="email" placeholder="Email" value={email} onChange={e=>setEmail(e.target.value)}/><input required minLength={8} type="password" placeholder="Password" value={pw} onChange={e=>setPw(e.target.value)}/>{error&&<div className="error">{error}</div>}<button>{register?'Create account':'Sign in'}</button><button type="button" className="secondary" onClick={()=>setRegister(!register)}>{register?'Already have an account?':'Create an account'}</button></form></div>}
function Layout({user,logout}:{user:User;logout:()=>void}){return <div className="layout"><aside><h2>RAG<span>Forge</span></h2><div className="muted">{user.email}</div><nav><Link to="/">Dashboard</Link><Link to="/documents">Documents</Link><Link to="/search">Hybrid Search</Link><Link to="/chat">RAG Chat</Link><Link to="/evaluation">Evaluation</Link></nav><button className="secondary" onClick={logout}>Logout</button></aside><main><Routes><Route path="/" element={<Dashboard/>}/><Route path="/documents" element={<Documents/>}/><Route path="/search" element={<Search/>}/><Route path="/chat" element={<Chat/>}/><Route path="/evaluation" element={<Evaluation/>}/></Routes></main></div>}
function Dashboard(){return <><div className="hero"><div><div className="eyebrow">RAG PIPELINE</div><h1>Document intelligence you can inspect.</h1><p>Documents → Smart Chunking → BM25 + Vector Search → Hybrid RRF → Reranker → LLM → Citation Verification → Answer</p></div></div><div className="grid">{[['📄','Documents','PDF, TXT and DOCX ingestion'],['✂️','Smart Chunking','Overlap-aware chunks with page metadata'],['🔎','Hybrid Retrieval','BM25 + dense vectors + RRF'],['🎯','Reranker','Cross-Encoder relevance scoring'],['🤖','Grounded LLM','Context-constrained generation'],['📚','Citations','Source mapping and verification']].map(([i,t,d])=><div className="card feature" key={t}><div className="icon">{i}</div><h3>{t}</h3><p>{d}</p></div>)}</div></>}
function Documents(){const[docs,setDocs]=useState<Doc[]>([]);const[file,setFile]=useState<File|null>(null);const[msg,setMsg]=useState('');const load=async()=>setDocs((await api.get('/documents')).data);useEffect(()=>{load()},[]);async function upload(){if(!file)return;const f=new FormData();f.append('file',file);setMsg('Processing document...');try{const r=await api.post('/documents/upload',f);setMsg(`${r.data.chunk_count} chunks indexed`);setFile(null);await load()}catch(e:any){setMsg(e.response?.data?.detail||'Upload failed')}}async function del(id:number){await api.delete(`/documents/${id}`);load()}return <><h1>Documents</h1><p className="muted">Upload sources for the RAG pipeline.</p><div className="card"><input type="file" accept=".pdf,.txt,.docx" onChange={e=>setFile(e.target.files?.[0]||null)}/><button onClick={upload}>Upload & Index</button><span className="status">{msg}</span></div>{docs.map(d=><div className="card row" key={d.id}><div><b>{d.filename}</b><div className="muted">{d.status} · {d.chunk_count} chunks</div>{d.error_message&&<div className="error">{d.error_message}</div>}</div><button className="danger" onClick={()=>del(d.id)}>Delete</button></div>)}</>}
function Search(){const[q,setQ]=useState('');const[r,setR]=useState<any[]>([]);async function go(){if(q.trim())setR((await api.post('/search',{query:q,top_k:10})).data.results)}return <><h1>Hybrid Search</h1><div className="bar"><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search your indexed documents" onKeyDown={e=>e.key==='Enter'&&go()}/><button onClick={go}>Search</button></div>{r.map((x,i)=><div className="card source" key={i}><div className="sourcehead"><b>{x.document}</b><span>RRF {Number(x.rrf_score).toFixed(4)}</span></div><p>{x.text}</p><small>Page: {x.page??'N/A'} · Chunk: {x.chunk_id}</small></div>)}</>}
function Chat(){const[q,setQ]=useState('');const[r,setR]=useState<any>(null);const[loading,setLoading]=useState(false);async function ask(){if(!q.trim())return;setLoading(true);try{setR((await api.post('/chat',{question:q,top_k:5})).data)}finally{setLoading(false)}}return <><h1>Grounded RAG Chat</h1><div className="card"><textarea rows={5} value={q} onChange={e=>setQ(e.target.value)} placeholder="Ask a question about your uploaded documents..."/><button onClick={ask} disabled={loading}>{loading?'Retrieving + reranking...':'Ask RAGForge'}</button></div>{r&&<><div className="card answer"><div className="eyebrow">GROUNDED ANSWER</div><p>{r.answer}</p><div className="muted">{r.latency_ms} ms · {r.retrieval_count} final sources</div></div><h2>Citations</h2>{r.citations.map((c:any)=><div className="card citation" key={c.citation_id}><div className="sourcehead"><b>{c.citation_id} {c.document}</b><span className={c.verification==='supported'?'ok':''}>{c.verification}</span></div><p>Page {c.page??'N/A'}</p><p>{c.text}</p></div>)}</>}</>}
function Evaluation(){const[r,setR]=useState<any[]>([]);const load=async()=>setR((await api.get('/evaluation/results')).data);useEffect(()=>{load()},[]);async function run(){await api.post('/evaluation/run');load()}return <><h1>Evaluation</h1><p className="muted">Track retrieval and citation evaluation results.</p><button onClick={run}>Run Baseline</button><div className="grid">{r.map(x=><div className="card" key={x.id}><h3>{x.dataset_name}</h3><p>Precision@K: {x.precision_at_k}</p><p>Recall@K: {x.recall_at_k}</p><p>Hit Rate: {x.hit_rate}</p><p>MRR: {x.mrr}</p><p>Citation Accuracy: {x.citation_accuracy}</p><p>Unsupported Claim Rate: {x.unsupported_claim_rate}</p></div>)}</div></>}
export default function App(){const[user,setUser]=useState<User|null>(null);const nav=useNavigate();useEffect(()=>{if(localStorage.getItem('rf_token'))api.get('/auth/me').then(r=>setUser(r.data)).catch(()=>localStorage.removeItem('rf_token'))},[]);if(!user)return <Auth onLogin={setUser}/>;function logout(){localStorage.removeItem('rf_token');setUser(null);nav('/')}return <Layout user={user} logout={logout}/>}
